### ISSUE TITLE
there isn't get_adata and barcode_use

### ISSUE THREAD

**Issue by gaotai8** [Durenlab/LINGER#19]
i am run GRN_infer.md. when i run adata_RNA,adata_ATAC=get_adata(matrix,features,barcodes,label)
>>> adata_RNA,adata_ATAC=get_adata(matrix,features,barcodes,label)
Traceback (most recent call last):
  File "/home/gaotai/conda/ENTER/envs/LINGER/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'barcode_use'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gaotai/conda/ENTER/envs/LINGER/lib/python3.10/site-packages/LingerGRN/preprocess.py", line 281, in get_adata
    adata_RNA=adata_RNA[adata_RNA.obs['barcode'].isin(label['barcode_use'].values)]
  File "/home/gaotai/conda/ENTER/envs/LINGER/lib/python3.10/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/gaotai/conda/ENTER/envs/LINGER/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'barcode_use'
can you tell me how can i solve it? Thank you!!!

**Comment by gaotai8** [comment]
i want see get_adata, but i can't find it

**Comment by amssyqy** [comment]
Thanks for your question~
The column name of label is ['barcode_use','label'] 
![label](https://github.com/Durenlab/LINGER/assets/43508437/c95cb747-2c3e-4e63-84bf-4013f01fbde2)
You could set it by `label.columns=['barcode_use','label'] `

**Comment by LinLi-0909** [comment]
I can not find get_adata function in preproposs.py
