### ISSUE TITLE
there isn't find_neighbors()

### ISSUE THREAD

**Issue by gaotai8** [Durenlab/LINGER#21]
i want run pbmc.md
adata RNA,adata ATAC=find neighbors(adata RNA,adata ATAC)
Traceback(most recent call last):File"<stdin>",line 1,in <module>
NameError: name 'find neighbors' is not defined

**Comment by feanaros** [comment]
Hi, change the 'from pseudo_bulk import *'  to 'from LingerGRN.pseudo_bulk import *'

**Comment by gaotai8** [comment]
> Hi, change the 'from pseudo_bulk import *' to 'from LingerGRN.pseudo_bulk import *'

Hi,the question still remains
>>> import scanpy as sc
>>> sc.settings.set_figure_params(dpi=80, frameon=False, figsize=(5, 5), facecolor='white')
>>> sc.settings.verbosity = 3  # verbosity: errors (0), warnings (1), info (2), hints (3)
>>> sc.logging.print_header()
scanpy==1.9.5 anndata==0.9.2 umap==0.5.6 numpy==1.24.3 scipy==1.11.3 pandas==2.0.3 scikit-learn==1.3.0 statsmodels==0.14.1 pynndescent==0.5.12
>>> import scipy
>>> import pandas as pd
>>> matrix=scipy.io.mmread('data/filtered_feature_bc_matrix/matrix.mtx')
>>> features=pd.read_csv('data/filtered_feature_bc_matrix/features.tsv',sep='\t',header=None)
>>> barcodes=pd.read_csv('data/filtered_feature_bc_matrix/barcodes.tsv',sep='\t',header=None)
>>> label=pd.read_csv('data/PBMC_label.txt',sep='\t',header=0)
>>> from LingerGRN.pseudo_bulk import *
>>> adata_RNA,adata_ATAC=get_adata(matrix,features,barcodes,label)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'get_adata' is not defined

**Comment by amssyqy** [comment]
Thanks for using LINGER!
Please try to install the latest released version:
```sh
pip install LingerGRN==1.52
```

**Comment by gaotai8** [comment]
> 感谢您使用 LINGER！ 请尝试安装最新发布的版本：
> 
> ```shell
> pip install LingerGRN==1.52
> ```

thank you!! i solve it, but there is a another question about pseudo_bulk()
for tempsample in samplelist:
...     adata_RNAtemp=adata_RNA[adata_RNA.obs['sample']==tempsample]
...     adata_ATACtemp=adata_ATAC[adata_ATAC.obs['sample']==tempsample]
...     TG_pseudobulk_temp,RE_pseudobulk_temp=pseudo_bulk(adata_RNAtemp,adata_ATACtemp,singlepseudobulk)
...     TG_pseudobulk=pd.concat([TG_pseudobulk, TG_pseudobulk_temp], axis=1)
...     RE_pseudobulk=pd.concat([RE_pseudobulk, RE_pseudobulk_temp], axis=1)
...     RE_pseudobulk[RE_pseudobulk > 100] = 100
...
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
TypeError: pseudo_bulk() takes 2 positional arguments but 3 were given

**Comment by Therabbiteating** [comment]
I'm encountering the same issue. Any suggestions on how to resolve it? looking forward to your reply. ^^

**Comment by Therabbiteating** [comment]
I'm encountering the same issue. Any suggestions on how to resolve it? looking forward to your reply. ^^

Traceback (most recent call last):
File "", line 4, in
TypeError: pseudo_bulk() takes 2 positional arguments but 3 were given
