### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'chr1_cell_population_TF_RE_binding.txt'

### ISSUE THREAD

**Issue by jessicaliu09** [Durenlab/LINGER#49]
Hi,

I'm using version 1.96,  and has the problem as following when running the PBMC tutorial: 
>>> LL_net.cell_type_specific_TF_RE_binding(GRNdir,adata_RNA,adata_ATAC,genome,celltype,outdir,method)# different from the previous version
  0%|                                                    | 0/23 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/LINGER/lib/python3.10/site-packages/LingerGRN/LL_net.py", line 517, in cell_type_specific_TF_RE_binding
    mat=pd.read_csv(outdir+chrN+'_cell_population_TF_RE_binding.txt',sep='\t',index_col=0,header=0)
  File "/LINGER/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/LINGER/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/LINGER/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/LINGER/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/LINGER/lib/python3.10/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'chr1_cell_population_TF_RE_binding.txt'

This error I think is from this step:
>>> LL_net.TF_RE_binding(GRNdir,adata_RNA,adata_ATAC,genome,method,outdir)
Generating cellular population TF binding strength ...
  0%|                                                    | 0/23 [00:00<?, ?it/s]
100%|███████████████████████████████████████████| 23/23 [00:34<00:00,  1.52s/it]
Generating cellular population TF binding strength for chrX
>>> 

Only chrX file was generated, but not for other chromosomes, can you help solve this problem, thanks.

**Comment by yojetsharma** [comment]
I am also facing this. Did you figure it out yet? Please help 
```
import LingerGRN.LL_net as LL_net
LL_net.cell_type_specific_TF_RE_binding(GRNdir,adata_RNA,adata_ATAC,genome,celltype,outdir,method)
Generate cell type specitic TF binding potential for cell type Radial-glia-3...

  0%|                                                                                                                                                                                                                           | 0/22 [00:00<?, ?it/s]

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[14], line 2
      1 import LingerGRN.LL_net as LL_net
----> 2 LL_net.cell_type_specific_TF_RE_binding(GRNdir,adata_RNA,adata_ATAC,genome,celltype,outdir,method)

File ~/miniconda3/envs/LINGER/lib/python3.10/site-packages/LingerGRN/LL_net.py:501, in cell_type_specific_TF_RE_binding(GRNdir, adata_RNA, adata_ATAC, genome, celltype, outdir, method)
    499     for i in tqdm(range(22)):
    500         chrN='chr'+str(i+1)
--> 501         mat=pd.read_csv(outdir+chrN+'_cell_population_TF_RE_binding.txt',sep='\t',index_col=0,header=0)
    502         out=cell_type_specific_TF_RE_binding_chr(adata_RNA,adata_ATAC,GRNdir,chrN,genome,label0,outdir,method,mat)
    503 #result=pd.concat([result,out],axis=1).fillna(0)

File ~/miniconda3/envs/LINGER/lib/python3.10/site-packages/pandas/io/parsers/readers.py:912, in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)
    899 kwds_defaults = _refine_defaults_read(
    900     dialect,
    901     delimiter,
   (...)
    908     dtype_backend=dtype_backend,
    909 )
    910 kwds.update(kwds_defaults)
--> 912 return _read(filepath_or_buffer, kwds)

File ~/miniconda3/envs/LINGER/lib/python3.10/site-packages/pandas/io/parsers/readers.py:577, in _read(filepath_or_buffer, kwds)
    574 _validate_names(kwds.get("names", None))
    576 # Create the parser.
--> 577 parser = TextFileReader(filepath_or_buffer, **kwds)
    579 if chunksize or iterator:
    580     return parser

File ~/miniconda3/envs/LINGER/lib/python3.10/site-packages/pandas/io/parsers/readers.py:1407, in TextFileReader.__init__(self, f, engine, **kwds)
   1404     self.options["has_index_names"] = kwds["has_index_names"]
   1406 self.handles: IOHandles | None = None
-> 1407 self._engine = self._make_engine(f, self.engine)

File ~/miniconda3/envs/LINGER/lib/python3.10/site-packages/pandas/io/parsers/readers.py:1661, in TextFileReader._make_engine(self, f, engine)
   1659     if "b" not in mode:
   1660         mode += "b"
-> 1661 self.handles = get_handle(
   1662     f,
   1663     mode,
   1664     encoding=self.options.get("encoding", None),
   1665     compression=self.options.get("compression", None),
   1666     memory_map=self.options.get("memory_map", False),
   1667     is_text=is_text,
   1668     errors=self.options.get("encoding_errors", "strict"),
   1669     storage_options=self.options.get("storage_options", None),
   1670 )
   1671 assert self.handles is not None
   1672 f = self.handles.handle

File ~/miniconda3/envs/LINGER/lib/python3.10/site-packages/pandas/io/common.py:859, in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    854 elif isinstance(handle, str):
    855     # Check whether the filename is to be opened in binary mode.
    856     # Binary mode does not support 'encoding' and 'newline'.
    857     if ioargs.encoding and "b" not in ioargs.mode:
    858         # Encoding
--> 859         handle = open(
    860             handle,
    861             ioargs.mode,
    862             encoding=ioargs.encoding,
    863             errors=errors,
    864             newline="",
    865         )
    866     else:
    867         # Binary mode
    868         handle = open(handle, ioargs.mode)

FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Desktop/linger/chr1_cell_population_TF_RE_binding.txt'
```

**Comment by aduvie** [comment]
I had this same problem. From what I could tell, the file generated in the previous step: LL_net.TF_RE_binding(GRNdir,adata_RNA,adata_ATAC,genome,method,outdir) generates a single file called cell_population_TF_RE_binding.txt. But the next step is expecting this file to be split into individual chromosomes. My fix was to use this bash command:

awk 'NR==1 {header=$0; next} {split($1, a, ":"); print header > (a[1] "_cell_population_TF_RE_binding.txt"); print >> (a[1] "_cell_population_TF_RE_binding.txt")}' cell_population_TF_RE_binding.txt

Which splits the file into the properly named files based on the chromosome numbers. Hope this helps!

**Comment by yojetsharma** [comment]
Yes! So since your workaround is to make this change in the source code, can you tell me for to look for the source code?

**Comment by aduvie** [comment]
Not source code, just a bash workaround to split the file after it's made. Looking at other people's posts however, it looks like the most recent versions are just bugged though. It might also be easier to switch to an earlier version like 1.69

**Comment by yojetsharma** [comment]
Understood, thanks for this.l! Will update right back when I downgrade it to 1.69.

**Comment by yojetsharma** [comment]
> Not source code, just a bash workaround to split the file after it's made. Looking at other people's posts however, it looks like the most recent versions are just bugged though. It might also be easier to switch to an earlier version like 1.69

Upon using a different version, gave me another error, so will split the file as you suggested earlier. 
the error (v1.69):
```
Generate cell type specitic TF binding potential for cell type Glioblast-2...

  0%|                                                                                                                 | 0/22 [06:26<?, ?it/s]

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[21], line 2
      1 import LingerGRN.LL_net as LL_net
----> 2 LL_net.cell_type_specific_TF_RE_binding(GRNdir, adata_RNA,adata_ATAC, genome,celltype, outdir,method)

File ~/.conda/envs/besca/lib/python3.10/site-packages/LingerGRN/LL_net.py:349, in cell_type_specific_TF_RE_binding(GRNdir, adata_RNA, adata_ATAC, genome, celltype, outdir, method)
    347     for i in tqdm(range(22)):
    348         chrN='chr'+str(i+1)
--> 349         out=cell_type_specific_TF_RE_binding_chr(adata_RNA,adata_ATAC,GRNdir,chrN,genome,label0,outdir,method)
    350 #result=pd.concat([result,out],axis=1).fillna(0)
    351         result = pd.concat([result, out], join='outer', axis=0)

File ~/.conda/envs/besca/lib/python3.10/site-packages/LingerGRN/LL_net.py:333, in cell_type_specific_TF_RE_binding_chr(adata_RNA, adata_ATAC, GRNdir, chrN, genome, celltype, outdir, method)
    331 RE_cluster=RE_cluster/RE_cluster.mean()
    332 RE_cluster = RE_cluster[:,None]
--> 333 S = np.log(RE_cluster+0.1) + np.log(mat+TFbinding+0.1) + np.log(TF_cluster+0.1)
    334 S = np.exp(S)
    335 S.index=N_overlap

File ~/.conda/envs/besca/lib/python3.10/site-packages/pandas/core/generic.py:2016, in NDFrame.__array_ufunc__(self, ufunc, method, *inputs, **kwargs)
   2012 @final
   2013 def __array_ufunc__(
   2014     self, ufunc: np.ufunc, method: str, *inputs: Any, **kwargs: Any
   2015 ):
-> 2016     return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)

File ~/.conda/envs/besca/lib/python3.10/site-packages/pandas/core/arraylike.py:273, in array_ufunc(self, ufunc, method, *inputs, **kwargs)
    270 kwargs = _standardize_out_kwarg(**kwargs)
    272 # for binary ops, use our custom dunder methods
--> 273 result = maybe_dispatch_ufunc_to_dunder_op(self, ufunc, method, *inputs, **kwargs)
    274 if result is not NotImplemented:
    275     return result

File ~/.conda/envs/besca/lib/python3.10/site-packages/pandas/_libs/ops_dispatch.pyx:113, in pandas._libs.ops_dispatch.maybe_dispatch_ufunc_to_dunder_op()

File ~/.conda/envs/besca/lib/python3.10/site-packages/pandas/core/ops/common.py:81, in _unpack_zerodim_and_defer.<locals>.new_method(self, other)
     77             return NotImplemented
     79 other = item_from_zerodim(other)
---> 81 return method(self, other)

File ~/.conda/envs/besca/lib/python3.10/site-packages/pandas/core/arraylike.py:190, in OpsMixin.__radd__(self, other)
    188 @unpack_zerodim_and_defer("__radd__")
    189 def __radd__(self, other):
--> 190     return self._arith_method(other, roperator.radd)

File ~/.conda/envs/besca/lib/python3.10/site-packages/pandas/core/frame.py:7455, in DataFrame._arith_method(self, other, op)
   7452 axis: Literal[1] = 1  # only relevant for Series other case
   7453 other = ops.maybe_prepare_scalar_for_op(other, (self.shape[axis],))
-> 7455 self, other = ops.align_method_FRAME(self, other, axis, flex=True, level=None)
   7457 new_data = self._dispatch_frame_op(other, op, axis=axis)
   7458 return self._construct_result(new_data)

File ~/.conda/envs/besca/lib/python3.10/site-packages/pandas/core/ops/__init__.py:288, in align_method_FRAME(left, right, axis, flex, level)
    285         right = to_series(right[0, :])
    287     else:
--> 288         raise ValueError(
    289             "Unable to coerce to DataFrame, shape "
    290             f"must be {left.shape}: given {right.shape}"
    291         )
    293 elif right.ndim > 2:
    294     raise ValueError(
    295         "Unable to coerce to Series/DataFrame, "
    296         f"dimension must be <= 2: {right.shape}"
    297     )

ValueError: Unable to coerce to DataFrame, shape must be (909722, 579): given (454861, 1)

```

**Comment by jessicaliu09** [comment]
Thanks, Alexander, your code is the temporary solution!
