### ISSUE TITLE
Issue with preprocess

### ISSUE THREAD

**Issue by danielcgingerich** [Durenlab/LINGER#53]
Hello, 

I am encountering an issue with preprocess.  During generation of TF binding, I get an error
 ```
preprocess(TG_pseudobulk,RE_pseudobulk,GRNdir,genome,method,outdir)


Mapping gene expression...
Generate TF expression...
Generate RE chromatin accessibility...
Generate TF binding...
100%|████████████████████████████████████████| 23/23 [27:03<00:00, 70.60s/it]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hpc/group/adrc/dcg27/software/anaconda3/envs/LINGER/lib/python3.10/site-packages/LingerGRN/preprocess.py", line 235, in preprocess
    load_TFbinding(GRNdir,motifWeight,Match2,TFName,Element_name,outdir)
  File "/hpc/group/adrc/dcg27/software/anaconda3/envs/LINGER/lib/python3.10/site-packages/LingerGRN/preprocess.py", line 121, in load_TFbinding
    idx=Element_name_idx.loc[motif_binding.index][0].values
  File "/hpc/group/adrc/dcg27/software/anaconda3/envs/LINGER/lib/python3.10/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/hpc/group/adrc/dcg27/software/anaconda3/envs/LINGER/lib/python3.10/site-packages/pandas/core/indexing.py", line 1332, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/hpc/group/adrc/dcg27/software/anaconda3/envs/LINGER/lib/python3.10/site-packages/pandas/core/indexing.py", line 1272, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/hpc/group/adrc/dcg27/software/anaconda3/envs/LINGER/lib/python3.10/site-packages/pandas/core/indexing.py", line 1462, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "/hpc/group/adrc/dcg27/software/anaconda3/envs/LINGER/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5877, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/hpc/group/adrc/dcg27/software/anaconda3/envs/LINGER/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5938, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['chr10:100000012-100000559', 'chr10:100006167-100006835',\n       'chr10:100009138-100010604', 'chr10:100019859-100021165',\n       'chr10:100025433-100025960', 'chr10:100041631-100041921',\n       'chr10:100045787-100046520', 'chr10:100067361-100067831',\n       'chr10:100088917-100089585', 'chr10:100114678-100115357',\n       ...\n       'chrX:9940172-9941028', 'chrX:9947122-9947377', 'chrX:9948403-9949339',\n       'chrX:9954689-9955823', 'chrX:9980258-9980758', 'chrX:9981286-9981884',\n       'chrX:9983431-9983999', 'chrX:9986680-9987114', 'chrX:9995490-9996311',\n       'chrX:9997391-9997772'],\n      dtype='object', length=199312)] are in the [index]"

```

**Comment by abbey-green** [comment]
I am having the same issue! Not sure if it's from the merging or just from those indices not being in their bulk data...

**Comment by abbey-green** [comment]
In case you're still having problems, I figured out what my issue was! You have to put all your output files (psuedobulk, Peaks, etc) in the /data folder just as in the tutorial. I had a separate folder for my results and so it was pulling the Peak.txt from their tutorial data, not my data
