### ISSUE TITLE
TF_RE_binding

### ISSUE THREAD

**Issue by danielcgingerich** [Durenlab/LINGER#58]
`LL_net.TF_RE_binding(GRNdir,adata_RNA,adata_ATAC,genome,method,outdir)
`returns error message
```
Generating cellular population TF binding strength ...
0it [00:00, ?it/s]                                                                            | 0/23 [00:00<?, ?it/s]
  0%|                                                                                         | 0/23 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hpc/group/adrc/dcg27/software/anaconda3/envs/LINGER/lib/python3.10/site-packages/LingerGRN/LL_net.py", line 377, in TF_RE_binding
    mat=TF_RE_LINGER_chr(chrN,outdir)
  File "/hpc/group/adrc/dcg27/software/anaconda3/envs/LINGER/lib/python3.10/site-packages/LingerGRN/LL_net.py", line 231, in TF_RE_LINGER_chr
    ii=ii+1
UnboundLocalError: local variable 'ii' referenced before assignment
```

**Comment by lzj1769** [comment]
Same error. Any ideas to solve it?

**Comment by danielcgingerich** [comment]
@lzj1769 

Its a bug in line 231 of LL_net.py.   I changed `ii=ii+1` to `ii=len(range(times))`
I created my own LL_net.py and imported that as LL_net in my python script.
